[package]
name = "tanuki-cli"
version = "1.2.1"
edition = "2021"
authors = ["Mafifrizi <hazama3321@gmail.com>"]
description = "Deterministic Linux Active Directory triage engine"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Mafifrizi/tanuki"

[dependencies]

[[bin]]
name = "tanuki"
path = "src/main.rs"

[lib]
name = "tanuki"
path = "src/lib.rs"
